
name: Publish Update

on:
  push:
    branches: ["*"]

jobs:
  update:
    name: Update
    type: update
    params:
      branch: ${{ github.ref_name || 'test' }}
      message: ${{ github.event.head_commit.message }}
