export const workerTheme = {
    colors: {
        background: "#FFFFFF",
        foreground: "#0D0D0D",
        surface: "#FFFFFF",
        surfaceMuted: "#F2F2F2",
        surfaceInset: "#FAFAFA",
        border: "#E2E2E2",
        primary: "#D92B3A",
        primarySoft: "#FCEBEC",
        secondary: "#182540",
        secondarySoft: "#EEF2F7",
        mutedForeground: "#64748B",
        subtleForeground: "#94A3B8",
        destructive: "#BF1111",
        destructiveSoft: "#FEF2F2",
        warning: "#92400E",
        warningSoft: "#FEF3C7",
        success: "#166534",
        successSoft: "#DCFCE7",
        white: "#FFFFFF",
    },
    roleColors: ["#FDBA74", "#D8B4FE", "#FDA4AF", "#6EE7B7", "#FDE047", "#CBD5E1"],
} as const;
