-- OBSOLETE
-- Do not run this file.
--
-- The original Phase 1 SQL in this path referenced stale table names and an invalid
-- spatial index definition for the current jsonb coordinate model.
--
-- Replacement:
--   1. packages/database/drizzle/0001_solid_scorpion.sql
--   2. packages/database/scripts/apply-manual-migrations.ts
--
-- The manual migrator exists because the live schema fix requires
-- CREATE/DROP INDEX CONCURRENTLY, which Drizzle's transactional migrator cannot apply.
